- name: 測試 Playbook
  hosts: all
  become: true
  gather_facts: true
  vars: {}
  tasks:
    - name: Test task
      script: /Users/rayzang/Downloads/Ansible-web/ansible-web-platform/backend/ansible/scripts/test-script.sh
